### ISSUE TITLE
Slack Enhancements

### ISSUE THREAD

**Issue by leenooks** [botman/botman#258]
Hi, i've been playing with your bot quite a bit over the last couple of days, hoping to use it to help me complete a project I'm working on. It has saved me a lot of time, and helped me learning writing API clients to slack - thank you.

I'd like to suggest some enhancements - and when i get time, I'll provide a patch or two for you to review.

I'm focusing on creating slash commands and responding to them, as well as writing a bot - with the bot being used two ways: a) online and responding to messages, as well as b) sending one off messages.

Firstly, as per #251, it would be good if slack commands defaulted to using JSON responses. Currently it defaults to a text response and thus you cannot have any message formatting (https://api.slack.com/docs/message-formatting#message_formatting). This was a reasonably easy fix, but not sure if it affected the other ways of interacting with slack.

Secondly, (and I dont know the ramifications), but it would be good if say() returned the response from the server, not the BotMan object itself. I actually want to track the messages that I post (by grabbing the ID), so that I can latter add to the message (by referencing the ID in a message threads). Also, if I attempt to post to a private group, that the bot hasn't been invited to - I need the failure message to know that it wasn't posted.

Thirdly, I want to execute a post (as the bot), however, it is to send 1 (or more) messages, then exit on completion. It seems I need to initialise the RealTimeClient although I dont intend to use it. Not sure if there is another way of doing that?

Again, thanks for creating this, it's been very helpful.

**Comment by mpociot** [comment]
Hi Lee,

I just modified the way BotMan responds to Slack slash commands, and in the next version they will also use the JSON responses. I don't know why I switched to plain text, but JSON is much better.

I also plan to return the response objects instead of the BotMan object itself - but this would result in a breaking change. Even though I highly doubt, that the `reply` method gets chained right now. That's the main reason which is holding me back from doing this right now.

If you want to originate messages from your bot, you can already do that - given you have the User-ID of the receiver(s) - https://botman.io/1.5/sending#originating-messages

**Comment by Kcharle** [comment]
@mpociot when using `$botman->say('Message', 'my-recipient-user-id');` with slack, should the message not get sent to the user through the bot user? When I use the following code, the message comes back to me through slackbot and not my botman user.

```
$botman->hears('test', function($bot) {
    $bot->say('Message', 'U0343UZFU');
});
```

**Comment by robertBojor** [comment]
Having the same issue, but with conversations...

All messages come on the DM with "slackbot" but having the name of my bot.
