### ISSUE TITLE
Catching the end of a conversation

### ISSUE THREAD

**Issue by disc** [botman/botman#401]
Hello. Is there any way to catch the end of the conversation after calling $bot->startConversation(new MyConversation).
I mean how to get filled data from a conversation in the main thread?
For example, my bot asked some questions and I need to store answers to the database when the conversation was finished.
I tried to pass DI container to Conversation object, but it was unsuccessful.
Which way is proper:
1) Store answer to DB in Conversation class
2) Somehow returns data from conversation to main class?

**Comment by mpociot** [comment]
Well there is no real "main thread" so I would suggest that you save the answers in the conversation class.

**Comment by disc** [comment]
I'd like to save conversation result, but I can't.
How to properly pass DI container or my own handler to Conversation class?

**Comment by mpociot** [comment]
The problem is, that the conversation class gets serialized in order to persist the conversation state.
So whatever you save as properties in the conversation class needs to be serializable too - this could be the container itself as well. 

Let me know if that helps you.

If - whatever you're passing to the conversation class - can not be serialized, there's a new feature available soon, that lets you start a botman "listen" process which will spawn a socket connection.
It works similar to the way the Slack RTM API works right now.
