### ISSUE TITLE
Redundantly applying middleware

### ISSUE THREAD

**Issue by suushiemaniac** [botman/botman#445]
- BotMan Version: 1.5.7
- PHP Version: 7.0.20
- Messaging Service(s): any
- Cache Driver: N/A

### Description:
Upon closer inspection, the `listen()` method in `BotMan.php` first applies all registered middlewares and _then_ checks for compliance by channel, driver, `hears` pattern etc.
When using an `API.AI` middleware, this implies that **ALL** chat input gets sent to (and thus evaluated by) API.AI eventually, which is definitely a no-go in terms of confidentiality in enterprise Slack solutions.

### Steps To Reproduce:
Create any BotMan integration and add an API.AI middleware to it. Then interact with the bot.

### Remarks:
I understand that the `isMessageMatching` method requires the middleware to be applied already, but the `isDriverValid` and `isChannelValid` methods in my opinion don't. Or should a middleware be allowed to alter the `getChannel()` (aka `getRecipient()`) result?!
If you agree, I can create a pull request splitting up the main `if` clause into two separate `if` clauses where the middleware only gets applied if really necessary (i.e. after the first if clause is passed)

**Comment by mpociot** [comment]
Have you looked into the source for the upcoming 2.0 release?

The middleware does get applied a bit different with the upcoming version, but as you mentioned: 

If you want to use API.ai **all** messages need to be passed to API.ai. Because otherwise, it's impossible to know if the message is matching or not.

If enterprise Slack confidentiality is an issue, I would highly recommend to use a self-hosted API.ai alternative instead. There is a great drop-in replacement called "Rasa NLU": https://rasa.ai

I don't think that this behaviour can be changed.
In 2.0 it works like this:

https://github.com/botman/botman/blob/master/src/Commands/ConversationManager.php#L74-L84

When receiving the messages, they all get passed to the new "received" middleware - which for example processes them at API.ai.
**Then** the messages go to the Matcher class where it checks if the Pattern, Driver or Recipient match. 

The`isChannelValid` method no longer exists in 2.0 because of two reasons:
- It was not documented at all (which isn't that imported)
- It is very driver (Slack) specific.

Instead I want to provide a built-in middleware for Slack, that allows you to filter out messages that don't match.

**Comment by suushiemaniac** [comment]
Thank you for the prompt answer. I will have a look into the "Rasa NLU" project you posted.
However, I have not tampered with the 2.0 source at all, because I've been working on 1.5.* versions all the time.

I recon my basic issue still persists: It would be best to first check compliance to things like driver that can't be altered by middleware, then apply middleware to the message and check the remaining part afterwards. This is opposed to the "check everything in one method call" approach you presented in the 2.0 link (line 80 at the time of writing this post).

**Comment by suushiemaniac** [comment]
Closely related to this, I also realised that for each `listenTo` entry (bear with me for using 1.5.7 terminology :innocent:) a received message gets looped through the middleware again and again despite not changing within the inner `listen()` loop. This led to a massive deterioration in performance (7+ requests vs. 1) and had me introduce a separate "middleware-d" message cache inside the `hears()` method

**Comment by mpociot** [comment]
In 2.0 the received messages no longer get looped through the middleware all over again - only once per received message.

But again - I am not sure that this will work. The middleware receives the `IncomingMessage` object and passes it to the `$next` variable.

So you could _theoretically_ swap out the incoming message with a completely new object, thus previous checks might be false: https://github.com/botman/botman/blob/master/src/Interfaces/MiddlewareInterface.php#L30

What we could do is this: Swap the if condition order in the message matcher class: https://github.com/botman/botman/blob/master/src/Messages/Matcher.php#L33-L35

This way, if for example the driver is invalid, the remaining methods will not be executed.
