### ISSUE TITLE
Conversation started as the @slackbot user, not my bot

### ISSUE THREAD

**Issue by kielabokkie** [botman/botman#469]
- BotMan Version: 1.5.1
- PHP Version: 7.1
- Messaging Service(s): Slack
- Cache Driver:

### Description:
I'm using Laravel and have the following route:

    Route::get('/test', function () {
        $botman = app('botman');
        $botman->startConversation(new TestConversation(), '@wouter', SlackDriver::class);
    });

When I hit the `/test` endpoint the `TestConversation` is started but the problem is that it is started at the `@slackbot` user, not the bot that I've created. This messes with the reply functionality and the conversation gets stuck on the first message. Any idea how to start a conversation this way as my own bot user?

**Comment by dFayet** [comment]
I have the same behavior on master, with conversion, or with the following snippet
`$botman->say('Message', '@XXXXXXXXXX', SlackDriver::class);`

**Comment by dFayet** [comment]
Alright, I have found the solution
For both case we need to add `'as_user' => true` in the additionals parameters.

For my case : 
`$botman->say('Message', 'xxxxxxx', SlackDriver::class, ['as_user'=>true]);`

And for a conversation case
```
public function askFirstname()
{
    $this->ask('Hello! What is your firstname?', function(Answer $answer) {
        // Save result
        $this->firstname = $answer->getText();
   
       $this->say('Nice to meet you '.$this->firstname);
        $this->askEmail();
    }, ['as_user' => true]);
}
```

There is a part in the slack api doc https://api.slack.com/methods/chat.postMessage#authorship talking about this setting, by default set to `false`.

I actually don't know if we have this behavior because of the bot configuration (slack integration) or if this is the "standard" use and maybe we should set the `as_user => true` by default in the `reply()` functions.

Any thoughts @mpociot ?

**Comment by mpociot** [comment]
@dFayet I think this depends a lot on the integration method.
As the Slack documentation says, the token that you use defines if you can post as the user or not.
I will add this to the slack driver in master. If someone doesn't want this behaviour it's still easy to just turn it off by using the additional parameters.
