### ISSUE TITLE
Botman without message provider

### ISSUE THREAD

**Issue by mybigman** [botman/botman#501]
Hi,

I recently came across this package and it looks fantastic.

Can I use botman without a message service like FB, slack etc; just using its own inbuilt system?

Is it as simple as sending an ajax "GET/POST" request to a controller method and return the response?

Any documentation or working sample on doing this and are there any decent chat UI's to use.

Thanks.

**Comment by mpociot** [comment]
Yes! There is a web driver available for BotMan 2.0 that allows you to do just that.
It will also be included in the upcoming BotMan Studio release so that you can test your chatbot out of the box.

2.0 will be released at the end of the month. If you want to take a look at how the web driver is implemented:

Driver: https://github.com/botman/driver-web

VueJS web driver component: https://github.com/botman/studio/blob/2.0/resources/assets/js/components/BotManTinker.vue
