### ISSUE TITLE
Use BotMan behind a corporate proxy

### ISSUE THREAD

**Issue by charlieboygis** [botman/botman#520]
- BotMan Version: 2
- PHP Version: 7.1
- Messaging Service(s): Fb, Telegram
- Cache Driver: File

### Description:
Working behind a corporate proxy I need to set the CURLOPT_PROXY setting (via curl_setopt) editing the src/Http/Curl class (prepareRequest method). Is there a way to extend only this class or to add a configuration property somewhere, without touching any vendor file?

### Steps To Reproduce:
Try to run some bot behind a corporate proxy

P.S.: Thanks for this awesome, well written library!

**Comment by mpociot** [comment]
How do you create the BotMan instance from the factory? Are you using BotMan studio?

You can pass the Curl instance to the BotMan factory.

**Comment by charlieboygis** [comment]
I'm building my bot over BotMan studio. Can you give me a hint?
Thank you.

**Comment by mpociot** [comment]
Sure. 

BotMan Studio loads the BotManServiceProvider in your config/app.php

The service provider loads BotMan through the factory. And the factory create method ibstanciates curl. 

https://github.com/botman/botman/blob/master/src/BotManServiceProvider.php#L21

So just create your own service provider instead of the BotMan one and use the custom creation code. 

https://github.com/botman/botman/blob/master/src/BotManFactory.php#L67

**Comment by charlieboygis** [comment]
IOC is the anwser!
This way, as you said on another issue, I will also be able tu support different bots from a single app.
Thank you so much!
