### ISSUE TITLE
withAttachment($image) - Image not displayed

### ISSUE THREAD

**Issue by RickD123** [botman/botman#587]
- BotMan Version: 2.1.2
- PHP Version: 5.6
- Messaging Service(s): Web
- Cache Driver:

### Description:
Hi,

I am trying to send a message to the user with an image, however for some reason the attachment is missing (the text is displayed however). Here is the code:

```

use App\Http\Controllers\BotManController;
use BotMan\BotMan\Messages\Attachments\Image;
use BotMan\BotMan\Messages\Outgoing\OutgoingMessage;

$botman->hears('image', function ($bot) {

    $bot->typesAndWaits(1);

    $image = Image::url('https://www.codeproject.com/KB/GDI-plus/ImageProcessing2/flip.jpg')->title('Cute dog');
    $message = OutgoingMessage::create('This is a cute dog.')->withAttachment($image);
    $bot->reply($message);

});


```

Thanks for your help.

Best regards
RickD

### Steps To Reproduce:

**Comment by christophrumpel** [comment]
Hey @RickD123,

I guess you are using BotMan Tinker again as the frontend? This is just an example of how you could implement a frontend to work with the BotMan WebDriver. It only supports text und you need yourself to work on the visualization of all the BotMan features.

**Comment by RickD123** [comment]
Well, I am having the same effect with "php artisan serve" - would you be able to point me into the right direction on how to implement a frontend that allows images to be displayed?

**Comment by christophrumpel** [comment]
This is not that easy to say unfortunately. The WebDriver is an easy to use API for a lot of BotMan functionalities. You need to have experiences with a JavaScript Framework in order to decide what to do with that api information. In my case I have a frontend team who can use this api and they decide how to implement in. If you have experiences with vuejs than the best way would be to try to extend BotMan Tinker. I think best way would be to ask about that in the Slack channel for Botman, this is what the channel is for. Here on GitHub we only want to dicuss issues. Hope someone from the Slack channel can help 👍
