### ISSUE TITLE
Proposal: ORM to test

### ISSUE THREAD

**Issue by francescobianco** [botman/botman#590]
I'm so sorry to disturb you, I would kindly ask you if you could test this library in your project! 
https://github.com/javanile/moldable
With the purpose of knowing my project and understanding if it can be integrated into yours!
To thank you for your availability I am observing your project and giving a star

Install via composer
```
composer require javanile/moldable
```

I ask you if we can help each other

**Comment by christophrumpel** [comment]
Hey @francescobianco ,
we already support the Laravel framework with the BotMan Studio solution. So there we recommend the ORM Eloquent. But since BotMan can be used with any PHP framework or project, everyone can decide for himself how to use a database. I don't think it would make sense to recommend another ORM. But you can come to our Slack channel and discuss with BotMan users about possibilities to use your project.
