### ISSUE TITLE
Middleware getUser : Unsupported get request (Facebook)

### ISSUE THREAD

**Issue by dimitribocquet** [botman/botman#613]
- BotMan Version: 2.1.3
- PHP Version: 7
- Messaging Service(s): Facebook
- Cache Driver: File

### Description:

In my middleware (Received), I'm trying to get the user :

```
$user = $bot->getUser();
$storage = $bot->userStorage();
$userStorage = $storage->find($user->getId());

if($userStorage->has('offence_warned')){
	if($userStorage->get('offence_warned') > 3){
		\Log::info('USER SUSPENDED');
		$bot->reply('You are suspended.');
	}else{
		\Log::info('USER ALLOWED');
		return $next($message);
	}
}
```

But I have this error for the first line :
`Error sending payload: Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api {"exception":"[object] (BotMan\\Drivers\\Facebook\\Exceptions\\FacebookException(code: 0): Error sending payload: Unsupported get request`

As you can see, I want to create a middleware to limit the number of offences. If the user offences the bot too many times, we reject his request with a message. Is it the good way to do it?

Thanks.

**Comment by mpociot** [comment]
Hi!

The error you received from Facebook often occurs when you try to get user information from a `user_ref` parameter instead of a real recipient ID. This happens for example in combination with the Facebook checkbox / opt in web plugin.

If all you need is the User-ID - and not any additional user information - you can use the `$message->getSender()` method instead.
This is the ID of the user that sent you the message.
