### ISSUE TITLE
Restricting Commands to Recipients Fails (no response)

### ISSUE THREAD

**Issue by jonathantittle** [botman/botman#702]
- BotMan Version: 2.1
- PHP Version: 7.2.1
- Messaging Service(s): Slack (via botman/driver-slack)
- Cache Driver: N/A

### Description:

When using botman/driver-slack to communicate with the bot, all works well except when I attempt to use the group method to limit specific responses to specific Slack ID's.

### Steps To Reproduce:

```
$botman->group(['recipient' => ['slack-id-01', 'slack-id-02']], function ( $bot ) {
    echo 'BotMan Group Method / Closure Call';

    $bot->hears('hello', function ( $bot ) {
        echo 'BotMan Hear Method / Closure Call';
        $bot->reply('Hi there!');
    });
});
```

The `echo`'s above were simply a means of output to the CLI when running the bot. I've tried using just the Slack ID of the user, the DM ID, and wrapping in both `<>` and `<@>` though nothing seems to work.

i.e.

```
['recipient' => ['111111111', '222222222']]
```
```
['recipient' => ['@111111111', '@222222222']]
```
```
['recipient' => ['<@111111111>', '<@222222222>']]
```

Am I missing something important here? :)

**Comment by rickkuilman** [comment]
Could you check for me if a single user works? Eg.

```
$botman->group(['recipient' => 'slack-id-01'], ...
```

**Comment by jonathantittle** [comment]
@rickkuilman Testing a single user does not work either unfortunately. Just ran `composer update` to ensure everything was up to date, though testing in-channel and via DM both fail to respond.

**Comment by leenooks** [comment]
I've done some debugging on this. I interpreted this feature to be that any slack messages sent to the bot - you could limit the bot from responding, unless the sender was in the array (aka "the recipient").

However, looking through/debugging the code - the recipient is the "bot's ID" - not the senders ID?

So if this is working as intended, it would be great to have an array of "senders" - so that commands and responses could be limited to a group of senders. Something like:

```
$botman->group(['sender' => ['slack-id-01', 'slack-id-02']], function ( $bot ) {
    $bot->hears('restart', function ( $bot ) {
        $bot->reply('OK, I'll restart!');
         die();
    });
});
```
