### ISSUE TITLE
Ho to deal with multiple conversations per one user?

### ISSUE THREAD

**Issue by tmoldri** [botman/botman#739]
- BotMan Version: 2.3.0
- PHP Version: 7.1
- Messaging Service(s): Facebook
- Cache Driver: Redis

### Description:
What to do about multiple conversations that are triggered by cron job or laravel queued job. I have conversation for asking users location or missing profile field, i also have conversation about updates on our website on specific events. How do i manage them not overlapping? What happens if one conversation is triggered while another is active? Is there a way to check if user has any open conversations?

**Comment by IacopoOrtis** [comment]
You just can't. Let's assume you have two active conversations. The user makes an input. Which one of the two are going to take the input ?

I suggest you to work with associative multy-dimensional arrays and one generic conversation. Basically you have for example 2 conversation with a decision tree and one conversation object able to reed a decision tree.

at runtime
step1) You turn on the first decision tree => conversation is created.
step2) You turn on the second decision tree => conversation assimilate the second tree.

and here you go. You have ONE conversation that in the reality is managing two decision tree.

The possible DOWNSIDE is the memory leverage in case of big projects. Solvable storing decision trees in different variables( stored in db/filesystem BUT NOT in the code obviously ).

**Comment by IacopoOrtis** [comment]
Wait a sec... did you tried to use skipsConversation() ?

**Comment by mkopinsky** [comment]
Conceptually having multiple conversations is a pain, and I agree with @IacopoOrtis that there isn't an easy standard approach.

However, I think there are a few things that could make it easier for apps, such as:

```php
    // current
    public function startConversation(Conversation $instance, $recipient = null, $driver = null);

    // proposed new methods
    public function getConversationForUser($recipient, $driver = null); // returns null if no active conversation
    public function stopConversationForUser($recipient, $driver = null);
    // or: 
    public function stopConversation(Conversation $instance);
```

so that in my app I can do stuff like:
```php
  public function onNonUrgentMessage($message)
  {
    if ($this->bot->getConversationForUser($recipient)) {
      $message->queueForLater(); // queue this again using my app's queue system
    } else {
      $this->bot->startConversation(new WhateverConversation, $recipient);
    }
  }
  
  public function onUrgentMessage($message)
  {
    if ($conversation = $this->bot->getConversationForUser($recipient)) {
      $this->bot->say('We interrupt your conversation to bring you this important message: ');
      $this->bot->stopConversation($conversation);
    } else {
      $this->bot->startConversation(new WhateverConversation, $recipient);
    }
  }
```

**Comment by mkopinsky** [comment]
If a PR to the above effect would be accepted, I (or my team at work) might work on it - we're exploring integrating Botman to our product, and being able to manage in-progress conversations is important to us.

**Comment by IacopoOrtis** [comment]
There is no need to use your solution. You can achieve the same goal creating an urgent conversation that pauses the less important conversations with the method skipsConversation or pauseConversation. Your solution and what I'm writing works only if you have a master conversation an many slaves.
I do not think this is what @tmoldri asked for. He/she wanted to have multiple conversations at the same time.

@tmoldri could you please be more specific? I assume you are not able to separate the two conversations just using regex. Am I right?

**Comment by mkopinsky** [comment]
Sorry, I wasn't clear in the description of my use case. By urgent and non-urgent message, I was referring to notifications generated directly from my system, whether through a cron job, or through actions of another user.

For example:
* Every morning at 9am we initiate a conversation with a user asking them how they are feeling today after their surgery. Today, they texted us at 8:59 asking us some other questions. Ideally, if like to see that they are mid-conversation and just reschedule the symptom questionnaire for 9:15.
* A patient responds saying they're having symptoms. The bot responds asking for more info, but we also notify a doctor who's monitoring the program. As soon as he logs in and responds to the patient, the automated conversation should halt.

In both cases, the trigger for the new conversation is from an outside action rather than from a message received by the bot, so I don't see a way to accomplish this using the skips/stopsConversation methods. What I am proposing is methods in the public API to accomplish this from outside the bot context, just like startConversation() can be used currently.
