### ISSUE TITLE
Facebook Messenger send multiple reply

### ISSUE THREAD

**Issue by Anan5a** [botman/botman#755]
Hi,
I'm using Botman to make a Facebook Messenger Bot. But whenever I send something to the webhook (send message from Facebook)  I get multiple replies. Sometimes it's over 500 msg each are same.
here's my code
```php
...
$botman->hears('search {q}',function (Botman $bot,$q){
$res = MLSID::search ($q);
$bot->reply($res);
});
$botman->listen ();

```

**Comment by christophrumpel** [comment]
Hey @Anan5a ,

when your BotMan application sends an error / 500 response back to FB, FB will try again and again to retry the request. This often leads to multiple messages. Please check your application logs for errors. The code looks fine but difficult to tell because I don't know what `MLSID::search` is doing in the back and you could miss namespaces as well. Please just check your logs.

**Comment by christophrumpel** [comment]
Are you using the BotMan Studio? What about the given example messages? Do they work? Or did it work sending back messages with other examples?

**Comment by Anan5a** [comment]
I'm not using botman studio.
The example messages work fine. no problem with simple text. if I use a parameter like 'foo {bar}' then the loop happens

**Comment by christophrumpel** [comment]
Hmm.. have you tried the same Code, just replacing $res with a string? Just to make sure it is not your method? In your code snippe is also a "spac" `$res = MLSID::search ($q);` is this in your code as well?

**Comment by salahy** [comment]
I had this issue before, it was problem with the firewall on the server
