### ISSUE TITLE
BotMan Facebook integration doesn't answer custom questions

### ISSUE THREAD

**Issue by tommiekn** [botman/botman#785]
- BotMan Version: 2.3.2
- PHP Version: 7.1
- Messaging Service(s): Facebook
- Cache Driver: File

### Description:
Without having edited anything for months i am having some issues, the bot doesn't reply anymore to any message manually typed by users, only the messenger menu works.

### Steps To Reproduce:
If i start a conversation from facebook with the provided call button, or , i do use the menu on facebook to call some action, it works and the bot replies but if i make a question manually typing the bot doesn't respond.
I have tried also writing call actions but nothing happen.

I have some debug log and it looks that the bot doesn't run at all while texting manually.
I have tried to update the app and laravel at the latest version but nothing changed.
Not sure if its some update FB side or so ?

Thanks

**Comment by tommiekn** [comment]
Following up with more tests, i can use the tinker with no problems, so i think this is an error between facebook and botman. As i haven't changed anything, but i know they are doing changes on the bots stuff,  could be that the reason ?

Anyone that use the facebook service having issues or knowing what this could be?

Thanks

**Comment by mpociot** [comment]
Hi,

please use GitHub issues only for issues with the library. 
If you have questions about how to use the library, join us on [Slack](https://slack.botman.io) or use the [Forum](https://botman.io/forum).

Thank you

**Comment by tommiekn** [comment]
@mpociot Hi, aren't these issues with the library? I do not have questions on how to use the library, i do have this issue to fix, as mentioned the bot was working fine. I've posted in the forum as well.

**Comment by mpociot** [comment]
Hi @tommiekn 

Well it sounds like it's an issue with Facebook, if you haven't changed any code and didn't update anything, this can't be releated to a code issue on this library.

Your issue sounds like it's coming from Facebook - and the past 2 years have shown that *weird* stuff happens with Facebook bots from time to time. You sometimes have to create new apps and link bots again in order to fix some of Facebook's issues. None of them are related to this github repository.

I just want to try and keep the GitHub issues focused on their main purpose: Showing / Discussing issues in this repositories codebase.

**Comment by tommiekn** [comment]
Hi @mpociot , totally understand and don't wanna get off topic, my question was here because i thought that this could be a bug in the Facebook integration, if thats the case i am offtopic still ?
It could be as you said or could be that they changed something on FB end and the Facebook connector of Botman needs some update because, i dont know so thats why i were asking :) 
Thanks!
