### ISSUE TITLE
Defending against infinite cycle

### ISSUE THREAD

**Issue by feralheart** [botman/botman#881]
- BotMan Version: 2
- PHP Version: 7.2
- Messaging Service(s): Facebook
- Cache Driver: file

### Description:
If Facebook sends an error for example "User not available at the moment" BotMan tries to resend the message in one minute. How to avoid it?

### Steps To Reproduce:

**Comment by christophrumpel** [comment]
the "infinite loop" happens when you have an error in your code and your application sends a 500 error to fb. fb then retries the request, and again and again. best thing to do is to immediately uncomment the code where the error happens so that your app can return a 200 code. then the loop will stop. cache:clear is only (additionally) necessary when you are inside a conversation.

I haven't noticed such a problem when FB sends an error message back. But every time it happens we throw an exception seen [here](https://github.com/botman/driver-facebook/blob/master/src/FacebookDriver.php#L499). In your application, you could catch that exception.

**Comment by mpociot** [comment]
If you're using Laravel, you can fix this by modifying the default exception handler to always return a 200 OK - even if it's not okay ;)

You can do this in your `app/Exceptions/Handler.php` file using:

```php
/**
 * Render an exception into an HTTP response.
 *
 * @param  \Illuminate\Http\Request  $request
 * @param  \Exception  $exception
 * @return \Illuminate\Http\Response
 */
public function render($request, Exception $exception)
{
    return parent::render($request, $exception)->setStatusCode(200);
}
```
