### ISSUE TITLE
Looking for a feature.  When a user does not reply a conversation.

### ISSUE THREAD

**Issue by adalessa** [botman/botman#900]
- BotMan Version: 2.0
- PHP Version: 7.1

### Description:
I am looking for a way to handles when a question during a conversation is no replied. I want to send a message before the conversations just gets deleted from the cache so the user knows that the conversation ended. Is there any callback that can be added to the ask in order to handle this?

**Comment by mpociot** [comment]
Hi,

this is not possible with BotMan - mostly due to the way that PHP works. When a user sends you a message, botman receives the incoming HTTP request - there's no way to call the "callback" at the time the conversation would be deleted from cache.

The best option would be to create a scheduled task yourself, where you check for unanswered conversations. For example by using the Laravel scheduler inside of BotMan Studio.
Then you could manually keep track of open conversations when you ask specific questions and use this information inside a cronjob.
