### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'BotMan\BotMan\Drivers\DriverManager' not found

### ISSUE THREAD

**Issue by direktornswe** [botman/botman#946]
- BotMan Version: 1.5
- PHP Version: 7.2.10
- Messaging Service(s): slack
- Cache Driver: n/a

### Description:
I have not been successful running botman outside of the "studio" implementation. I have tried a number of php versions and linux distributions. None of witch will be able to 

### Steps To Reproduce:
composer require botman/botman 1.5
composer require mpociot/slack-client 1

[run example code for slack]
PHP Fatal error:  Uncaught Error: Class 'BotMan\BotMan\Drivers\DriverManager' not found in /home/administrator/bajs/bot.php:17

Would it be possible on the wiki to explain the exact requirements as composer is broken by nature. It seems some extensions are required from zendframework but none are listed as requirements. 

Thanks!

**Comment by bertrandjamin** [comment]
@direktornswe Have you followed the dedicated documentation : https://botman.io/2.0/installation#basic-usage-without-botman-studio or https://botman.io/2.0/driver-slack#installation-setup? 

I have juste tested this with no problem :)

**Comment by keshon** [comment]
I faced similar issue. Fixed by adding `require_once __DIR__ . '/vendor/autoload.php';` on top of example file (eg bot.php)

**Comment by Gillu13** [comment]
@keshon's answer solves the issue I guess... but you may run into another "uncaught error" right after if you run the official documentation example since the Telegram driver is required but this fact is not explicitly stated in the current version of the doc ([2.0](https://botman.io/2.0/installation#basic-usage-without-botman-studio))

You've an extra composer requirement if you want the doc's example run with no error:

`composer require botman/driver-telegram`
